const E=(code,name,description,example,category='General',support='reference',insert=example)=>({code,name,description,example,category,support,insert});

export const CODES=[
  E('G00','Posicionamiento rápido','Movimiento rápido de uno o varios ejes.','G00 X0 Y0 Z50','Movimiento','full'),
  E('G01','Interpolación lineal','Movimiento recto con el avance F programado.','G01 X50 Y20 Z-2 F300','Movimiento','full'),
  E('G02','Interpolación circular horaria','Arco horario en el plano activo con I/J/K o R. También admite círculo completo omitiendo el punto final y usando I/J/K.','G17 G02 I-30 J0 F250','Movimiento','full'),
  E('G03','Interpolación circular antihoraria','Arco antihorario en el plano activo con I/J/K o R. También admite círculo completo omitiendo el punto final y usando I/J/K.','G17 G03 I-30 J0 F250','Movimiento','full'),
  E('G04','Permanencia','Detiene temporalmente la ejecución; normalmente usa P o X.','G04 P1000','Movimiento','partial'),
  E('G05.1','Control de contorno AI','Activa/desactiva funciones avanzadas de anticipación según control y opción.','G05.1 Q1','Alta velocidad','reference'),
  E('G07.1','Interpolación cilíndrica','Programa un desarrollo sobre una superficie cilíndrica; requiere opción/configuración.','G07.1 C25.0','Movimiento','reference'),
  E('G08','Control de anticipación','Función de look-ahead en controles/configuraciones compatibles.','G08 P1','Alta velocidad','reference'),
  E('G09','Parada exacta de un bloque','Fuerza comprobación de llegada al final del bloque actual.','G09 G01 X50 F300','Movimiento','reference'),
  E('G10','Entrada programable de datos','Escribe offsets o datos de control desde el programa. No genera movimiento; para interpolación lineal se usa G01.','G10 L2 P1 X0 Y0 Z0','Configuración','partial'),
  E('G11','Cancelar entrada de datos','Finaliza un modo de entrada de datos cuando aplica.','G11','Configuración','reference'),
  E('G15','Cancelar coordenadas polares','Cancela G16 y vuelve a interpretar X/Y como coordenadas cartesianas.','G15','Coordenadas','full'),
  E('G16','Coordenadas polares','Programa radio y ángulo desde el origen activo.','G16\nG01 X40 Y90 F300','Coordenadas','reference'),
  E('G17','Seleccionar plano XY','Plano para arcos, ciclos y compensación.','G17','Planos','full'),
  E('G18','Seleccionar plano XZ','Plano XZ para interpolación circular.','G18','Planos','full'),
  E('G19','Seleccionar plano YZ','Plano YZ para interpolación circular.','G19','Planos','full'),
  E('G20','Programación en pulgadas','Las dimensiones se interpretan en pulgadas.','G20','Unidades','full'),
  E('G21','Programación en milímetros','Las dimensiones se interpretan en milímetros.','G21','Unidades','full'),
  E('G22','Comprobación de carrera activada','Activa límites de recorrido programables cuando están configurados.','G22','Seguridad','reference'),
  E('G23','Comprobación de carrera cancelada','Cancela límites de recorrido programables.','G23','Seguridad','reference'),
  E('G27','Comprobación de retorno a referencia','Verifica que el eje alcance la referencia.','G27 X0 Y0 Z0','Referencia','reference'),
  E('G28','Retorno a referencia primaria','Regresa al cero máquina pasando por un punto intermedio.','G91 G28 Z0','Referencia','full'),
  E('G29','Retorno desde referencia','Regresa desde referencia hacia una posición indicada.','G29 X0 Y0','Referencia','reference'),
  E('G30','Retorno a referencia secundaria','Retorna a un segundo/tercer/cuarto punto de referencia usando P.','G30 P2 Z0','Referencia','reference'),
  E('G31','Salto de señal','Movimiento con captura de posición cuando aparece una señal externa.','G31 Z-50 F100','Medición','reference'),
  E('G37','Medición automática de longitud','Ciclo de medición de longitud de herramienta en configuraciones compatibles.','G37 Z-100','Medición','reference'),
  E('G40','Cancelar compensación de radio','Cancela G41/G42.','G40','Compensación','full'),
  E('G41','Compensación de radio izquierda','Compensa la trayectoria a la izquierda usando D.','G41 D03','Compensación','partial'),
  E('G42','Compensación de radio derecha','Compensa la trayectoria a la derecha usando D.','G42 D03','Compensación','partial'),
  E('G43','Compensación positiva de longitud','Aplica el corrector H de longitud de herramienta.','G43 H03 Z50','Compensación','full'),
  E('G43.4','Control del punto central de herramienta','TCP para mecanizado de cinco ejes; requiere control/opción compatible.','G43.4 H03','5 ejes','reference'),
  E('G43.5','Vector de herramienta','Control TCP mediante vector de dirección; requiere opción.','G43.5 H03','5 ejes','reference'),
  E('G44','Compensación negativa de longitud','Aplica compensación de longitud en dirección negativa.','G44 H03','Compensación','reference'),
  E('G49','Cancelar compensación de longitud','Cancela G43/G44.','G49','Compensación','full'),
  E('G50','Cancelar escalado','Cancela el escalado de coordenadas.','G50','Transformación','reference'),
  E('G50.1','Cancelar imagen espejo','Cancela la función espejo programable.','G50.1 X0 Y0','Transformación','reference'),
  E('G51','Escalado','Escala la geometría alrededor de un centro; sintaxis depende del control.','G51 X0 Y0 P2.0','Transformación','reference'),
  E('G51.1','Imagen espejo','Activa espejo programable en ejes especificados.','G51.1 X0','Transformación','reference'),
  E('G52','Sistema de coordenadas local','Añade un desplazamiento local al cero de pieza.','G52 X20 Y10 Z0','Coordenadas','full'),
  E('G53','Coordenadas máquina','Ejecuta el bloque sin aplicar el offset de trabajo.','G53 G00 Z0','Coordenadas','full'),
  E('G54','Cero de pieza 1','Selecciona el primer sistema de coordenadas de trabajo.','G54','Coordenadas','full'),
  E('G55','Cero de pieza 2','Selecciona el segundo sistema de coordenadas de trabajo.','G55','Coordenadas','full'),
  E('G56','Cero de pieza 3','Selecciona el tercer sistema de coordenadas de trabajo.','G56','Coordenadas','full'),
  E('G57','Cero de pieza 4','Selecciona el cuarto sistema de coordenadas de trabajo.','G57','Coordenadas','full'),
  E('G58','Cero de pieza 5','Selecciona el quinto sistema de coordenadas de trabajo.','G58','Coordenadas','full'),
  E('G59','Cero de pieza 6','Selecciona el sexto sistema de coordenadas de trabajo.','G59','Coordenadas','full'),
  E('G54.1','Offsets de trabajo adicionales','Selecciona offsets adicionales mediante P, normalmente P1–P48 si la opción está disponible.','G54.1 P1','Coordenadas','partial'),
  E('G61','Modo de parada exacta','Mantiene comprobación de llegada exacta hasta cancelación.','G61','Movimiento','reference'),
  E('G62','Control automático de esquinas','Ajusta el comportamiento en esquinas según configuración.','G62','Movimiento','reference'),
  E('G63','Modo de roscado','Modo especial para roscado rígido/operaciones relacionadas.','G63','Movimiento','reference'),
  E('G64','Modo de corte continuo','Prioriza continuidad del avance entre bloques.','G64','Movimiento','reference'),
  E('G65','Llamada a macro no modal','Llama un O-programa pasando argumentos a variables locales.','G65 P9000 A10 B20 X30','Macro','full'),
  E('G66','Llamada macro modal','Ejecuta la macro en bloques posteriores hasta G67.','G66 P9000 A10','Macro','reference'),
  E('G66.1','Llamada macro modal tipo II','Variante modal disponible en ciertos controles.','G66.1 P9000','Macro','reference'),
  E('G67','Cancelar macro modal','Cancela G66/G66.1.','G67','Macro','reference'),
  E('G68','Rotación de coordenadas','Rota el sistema de coordenadas alrededor de un centro.','G68 X0 Y0 R45','Transformación','full'),
  E('G68.2','Plano de trabajo inclinado','Define un plano inclinado para mecanizado multi-eje.','G68.2 X0 Y0 Z0 I0 J45 K0','5 ejes','reference'),
  E('G69','Cancelar rotación','Cancela G68/G68.2 según la configuración.','G69','Transformación','full'),
  E('G73','Taladrado profundo rápido','Ciclo de peck rápido con retracción corta.','G73 X20 Y20 Z-25 R2 Q5 F150','Ciclos fijos','full'),
  E('G74','Roscado izquierdo','Ciclo de roscado/tapping izquierdo en centros compatibles.','G74 X20 Y20 Z-15 R2 F100','Ciclos fijos','partial'),
  E('G76','Mandrinado fino','Ciclo de mandrinado fino; orientación/retiro depende de parámetros.','G76 X20 Y20 Z-12 R2 Q0.2 F80','Ciclos fijos','partial'),
  E('G80','Cancelar ciclo fijo','Cancela G73/G74/G76/G81–G89.','G80','Ciclos fijos','full'),
  E('G81','Taladrado simple','Rápido a R, avance hasta Z y retorno.','G81 X20 Y20 Z-10 R2 F150','Ciclos fijos','full'),
  E('G82','Taladrado con permanencia','Como G81, añadiendo pausa P en el fondo.','G82 X20 Y20 Z-10 R2 P500 F150','Ciclos fijos','full'),
  E('G83','Taladrado profundo con pecks','Taladra en incrementos Q y retira para evacuar viruta.','G83 X20 Y20 Z-30 R2 Q5 F120','Ciclos fijos','full'),
  E('G84','Roscado derecho','Ciclo de tapping derecho; requiere coordinación husillo-avance.','G84 X20 Y20 Z-15 R2 F100','Ciclos fijos','partial'),
  E('G85','Mandrinado entrada/salida con avance','Avanza al fondo y retorna con avance.','G85 X20 Y20 Z-12 R2 F80','Ciclos fijos','full'),
  E('G86','Mandrinado con paro de husillo','Avanza, detiene husillo y retorna rápido.','G86 X20 Y20 Z-12 R2 F80','Ciclos fijos','partial'),
  E('G87','Mandrinado posterior','Ciclo de back boring; depende de orientación y parámetros.','G87 X20 Y20 Z-12 R2 Q2 F80','Ciclos fijos','reference'),
  E('G88','Mandrinado con paro manual','Pausa en el fondo y espera intervención según el control.','G88 X20 Y20 Z-12 R2 P500 F80','Ciclos fijos','partial'),
  E('G89','Mandrinado con pausa y salida con avance','Añade permanencia en fondo y retorna con avance.','G89 X20 Y20 Z-12 R2 P500 F80','Ciclos fijos','full'),
  E('G90','Programación absoluta','Coordenadas medidas desde el cero activo.','G90','Coordenadas','full'),
  E('G91','Programación incremental','Cada coordenada indica un desplazamiento.','G91','Coordenadas','full'),
  E('G91.1','IJK incremental','Fuerza centros de arco I/J/K incrementales en controles compatibles.','G91.1','Movimiento','reference'),
  E('G92','Preajuste de coordenadas','Establece una relación temporal entre posición actual y coordenada programada.','G92 X0 Y0 Z0','Coordenadas','partial'),
  E('G94','Avance por minuto','F se interpreta como unidades por minuto.','G94','Avance','full'),
  E('G95','Avance por revolución','F se interpreta como unidades por revolución.','G95','Avance','reference'),
  E('G96','Velocidad superficial constante','Control de velocidad superficial; más común en torno o husillos configurados.','G96 S180','Husillo','reference'),
  E('G97','RPM constante','Cancela velocidad superficial constante.','G97 S3000','Husillo','reference'),
  E('G98','Retorno al nivel inicial','En ciclo fijo, retorna al Z inicial del ciclo.','G98 G81 X20 Y20 Z-10 R2 F150','Ciclos fijos','full'),
  E('G99','Retorno al plano R','En ciclo fijo, retorna al plano R.','G99 G81 X20 Y20 Z-10 R2 F150','Ciclos fijos','full'),

  E('M00','Paro programado','Detiene el programa hasta que el operador continúe.','M00','Funciones M','partial'),
  E('M01','Paro opcional','Detiene solo si Optional Stop está habilitado.','M01','Funciones M','partial'),
  E('M02','Fin de programa','Finaliza el programa sin la semántica completa de rebobinado de M30.','M02','Funciones M','partial'),
  E('M03','Husillo horario','Enciende husillo en sentido horario a S rpm.','M03 S6000','Funciones M','full'),
  E('M04','Husillo antihorario','Enciende husillo en sentido antihorario.','M04 S6000','Funciones M','full'),
  E('M05','Paro de husillo','Detiene el husillo.','M05','Funciones M','full'),
  E('M06','Cambio de herramienta','Ejecuta cambio a la herramienta T seleccionada.','T03 M06','Funciones M','full'),
  E('M07','Refrigerante de niebla','Activa niebla cuando la máquina la tiene configurada.','M07','Funciones M','reference'),
  E('M08','Refrigerante ON','Activa refrigerante principal.','M08','Funciones M','full'),
  E('M09','Refrigerante OFF','Desactiva refrigerante.','M09','Funciones M','full'),
  E('M10','Sujeción','Uso común para clamp; la función exacta la define el fabricante de la máquina.','M10','Funciones M','reference'),
  E('M11','Liberar sujeción','Uso común para unclamp; depende del fabricante.','M11','Funciones M','reference'),
  E('M19','Orientar husillo','Orienta el husillo a una posición definida.','M19','Funciones M','reference'),
  E('M29','Modo de roscado rígido','Prepara sincronización de husillo para tapping en muchas integraciones.','M29 S1000','Funciones M','reference'),
  E('M30','Fin y reinicio','Finaliza el programa principal y normalmente rebobina.','M30','Funciones M','full'),
  E('M48','Habilitar override','Habilita anulaciones de avance/husillo cuando la integración lo admite.','M48','Funciones M','reference'),
  E('M49','Deshabilitar override','Bloquea anulaciones programadas cuando está soportado.','M49','Funciones M','reference'),
  E('M60','Cambio de pallet','Función común de pallet; depende totalmente del constructor.','M60','Funciones M','reference'),
  E('M98','Llamada a subprograma','Llama O/P y puede repetir mediante L.','M98 P1000 L3','Subprogramas','full'),
  E('M99','Retorno de subprograma','Regresa al llamador o repite según el contexto.','M99','Subprogramas','full'),

  E('#','Variable Macro','Asigna o utiliza variables locales, comunes o de sistema.','#100 = 25.0','Macro','full','#100 = 0'),
  E('#1-#33','Variables locales','Variables locales usadas por argumentos de G65 y dentro de macros.','#1 = 10','Macro','full'),
  E('#100-#199','Variables comunes volátiles','Variables comunes que normalmente se borran al apagar, según configuración.','#100 = 5','Macro','full'),
  E('#500-#999','Variables comunes persistentes','Variables comunes que normalmente conservan valor tras apagado, según control.','#500 = 12.5','Macro','full'),
  E('#3000','Alarma Macro','Genera una alarma definida por el usuario.','#3000 = 1 (MENSAJE)','Macro','reference'),
  E('#3006','Mensaje/parada Macro','Muestra mensaje y detiene según la implementación.','#3006 = 1 (REVISAR PIEZA)','Macro','reference'),
  E('IF','Condición Macro','Ejecuta THEN o GOTO si una condición es verdadera.','IF [#100 LT -25] THEN #100 = -25','Macro','full'),
  E('THEN','Acción condicional','Parte de una asignación condicional IF.','IF [#1 EQ 0] THEN #1 = 1','Macro','full'),
  E('GOTO','Salto Macro','Salta a una etiqueta N dentro del programa actual.','IF [#100 EQ 0] GOTO100','Macro','full'),
  E('WHILE','Bucle Macro','Repite entre DO n y END n mientras la condición sea verdadera.','WHILE [#100 GT -25] DO1','Macro','full'),
  E('DO','Identificador de bucle','Asocia WHILE con su END correspondiente.','WHILE [#1 LT 10] DO1','Macro','full'),
  E('END','Fin de bucle','Cierra el bucle DO del mismo número.','END1','Macro','full'),
  E('EQ','Igual a','Operador relacional Macro.','IF [#1 EQ #2] GOTO100','Macro','full'),
  E('NE','Distinto de','Operador relacional Macro.','IF [#1 NE 0] GOTO100','Macro','full'),
  E('GT','Mayor que','Operador relacional Macro.','WHILE [#1 GT 0] DO1','Macro','full'),
  E('GE','Mayor o igual','Operador relacional Macro.','IF [#1 GE 10] GOTO100','Macro','full'),
  E('LT','Menor que','Operador relacional Macro.','IF [#1 LT 0] GOTO100','Macro','full'),
  E('LE','Menor o igual','Operador relacional Macro.','IF [#1 LE 10] GOTO100','Macro','full'),
  E('AND','Y lógico','Combina condiciones o valores binarios.','#3 = [#1 AND #2]','Macro','full'),
  E('OR','O lógico','Operador lógico Macro.','#3 = [#1 OR #2]','Macro','full'),
  E('XOR','O exclusiva','Operador lógico Macro.','#3 = [#1 XOR #2]','Macro','full'),
  E('MOD','Residuo','Obtiene el residuo de una división.','#2 = [#1 MOD 4]','Macro','full'),
  E('SIN','Seno','Función trigonométrica en grados.','#101 = SIN[30]','Macro','full'),
  E('COS','Coseno','Función trigonométrica en grados.','#101 = COS[45]','Macro','full'),
  E('TAN','Tangente','Función trigonométrica en grados.','#101 = TAN[15]','Macro','full'),
  E('ASIN','Arcoseno','Función inversa; disponibilidad/sintaxis puede variar.','#101 = ASIN[0.5]','Macro','reference'),
  E('ACOS','Arcocoseno','Función inversa; disponibilidad/sintaxis puede variar.','#101 = ACOS[0.5]','Macro','reference'),
  E('ATAN','Arcotangente','Función inversa; algunos controles aceptan formato de dos argumentos.','#101 = ATAN[1]','Macro','reference'),
  E('SQRT','Raíz cuadrada','Calcula raíz cuadrada.','#101 = SQRT[25]','Macro','full'),
  E('ABS','Valor absoluto','Devuelve magnitud sin signo.','#101 = ABS[#100]','Macro','full'),
  E('ROUND','Redondeo','Redondea al entero más cercano en expresiones.','#101 = ROUND[2.6]','Macro','full'),
  E('FIX','Redondeo hacia abajo','Elimina la parte decimal hacia menos infinito.','#101 = FIX[2.9]','Macro','full'),
  E('FUP','Redondeo hacia arriba','Redondea hacia más infinito.','#101 = FUP[2.1]','Macro','full'),
  E('LN','Logaritmo natural','Calcula logaritmo natural.','#101 = LN[10]','Macro','reference'),
  E('EXP','Exponencial','Calcula e elevado a un valor.','#101 = EXP[2]','Macro','reference'),

  E('X','Eje X','Coordenada o desplazamiento en X.','X50.0','Palabras','full'),
  E('Y','Eje Y','Coordenada o desplazamiento en Y.','Y25.0','Palabras','full'),
  E('Z','Eje Z','Coordenada o desplazamiento en Z.','Z-10.0','Palabras','full'),
  E('A','Eje/argumento A','Eje rotativo A o argumento Macro #1, según contexto.','A90.0','Palabras','reference'),
  E('B','Eje/argumento B','Eje rotativo B o argumento Macro #2.','B45.0','Palabras','reference'),
  E('C','Eje/argumento C','Eje rotativo C o argumento Macro #3.','C180.0','Palabras','reference'),
  E('F','Avance','Velocidad de avance según G94/G95.','F300','Palabras','full'),
  E('S','Velocidad de husillo','Comando de rpm o velocidad superficial según modo.','S6000','Palabras','full'),
  E('T','Número de herramienta','Selecciona herramienta.','T03','Palabras','full'),
  E('H','Corrector de longitud','Selecciona registro de longitud.','H03','Palabras','full'),
  E('D','Corrector de radio','Selecciona registro de diámetro/radio.','D03','Palabras','full'),
  E('I','Centro incremental X','Desplazamiento X al centro del arco; también argumento Macro.','I20.0','Palabras','full'),
  E('J','Centro incremental Y','Desplazamiento Y al centro del arco; también argumento Macro.','J0.0','Palabras','full'),
  E('K','Centro incremental Z','Desplazamiento Z al centro del arco; también argumento Macro.','K-10.0','Palabras','full'),
  E('R','Radio/plano R','Radio de arco o plano de referencia de ciclo.','R2.0','Palabras','full'),
  E('P','Número/tiempo/parámetro','Programa llamado, permanencia u otro parámetro según el código.','P1000','Palabras','full'),
  E('Q','Peck/desplazamiento','Profundidad de peck u otro parámetro de ciclo.','Q5.0','Palabras','full'),
  E('L','Repeticiones/dato auxiliar','Cantidad de repeticiones o selector para G10.','L3','Palabras','full'),
  E('N','Número de bloque','Etiqueta de bloque para lectura y GOTO.','N100','Palabras','full'),
  E('O','Número de programa','Identificador de programa o subprograma.','O1000','Palabras','full')
];

export const CODE_MAP=new Map(CODES.map(c=>[c.code,c]));
export const CATEGORIES=[...new Set(CODES.map(c=>c.category))].sort((a,b)=>a.localeCompare(b,'es'));
export const SUPPORT_LABELS={full:'Simulado',partial:'Parcial',reference:'Referencia'};
